### PR TITLE
Check OpenAI model name using their client

### LINKED ISSUE #499: Remove the check for invalid model names in the OpenAI API integration
This means we have to manually add models every time they come out. We might as well let the API call error if the model specified by the user does not exist.

### PR DESCRIPTION
**Pull request by remic33**
Check call usable openai models using openai API retrieval
close #499

### CODE REVIEW

**Comment by rlouf** [comment]
What API endpoint exactly?

**Comment by remic33** [comment]
> What API endpoint exactly?

GET https://api.openai.com/v1/models/{model}

**Comment by remic33** [comment]
@rlouf tests are broken because of Openai installation not recquired by config. Should I had it by default?

**Comment by rlouf** [comment]
Removing the [now deprecated test](https://github.com/outlines-dev/outlines/blob/0355ab4272a5d7e4d94c4a53a52593f885b81a61/tests/models/test_openai.py#L54) should be enough.

**Pull request closed without merging**
