### PR TITLE
Support min/max number of digits for numbers in JSON Schema

### LINKED ISSUE #847: For structuring JSON, I find the numbers (float/integers) are problematic with a consistent pattern of repetitive zeros
### Describe the issue as clearly as possible:

When I try to structure a JSON output to float, I will occasionally hit an error which upon inspection is caused by the field outputting a non-ending zeros such as:

```
{ "rating" : 0.0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
```

### Steps/code to reproduce the bug:

```python
It is occasional occurrence.
```

### Expected result:

```shell
Expected results will be 0.0
```

### Error message:

```shell
You will not be able to load this as JSON.


Error validating JSON: Invalid JSON
```
```


### Outlines/Python version information:

Python: 3.10.0
Outlines: 0.0.40

### Context for the issue:

_No response_

### PR DESCRIPTION
**Pull request by smagnan**
This would allow to mitigate some repetition issues that certain LLMs have. This should resolve #847

### CODE REVIEW

**Comment by rlouf** [comment]
Thank you for contributing! Would you mind adding some unit tests?

**Comment by smagnan** [comment]
> Thank you for contributing! Would you mind adding some unit tests?

Will do!

Should I also address the fixme I mentioned here? (ValueError not being raised when string minLength and maxLength are invalid), or should we have an other behavior? (Ignore the keys and add a warning for example)

**Comment by smagnan** [comment]
@rlouf Added unit tests for `integer` bounding and `number` (base and bounded).

Also one fix: first digit of integers was not counted towards the bounding.
And one adjustment: base and bounded number use the same rule for decimal places: `(\\.[0-9]+)` instead of `(\\.[0-9]*)`. Either can probably argued for but I am now using the same as the default one.

**Comment by rlouf** [comment]
Thanks! Looks like you need to fix the code style. Also could you _rebase_ the branch on `main`?

**Comment by smagnan** [comment]
PR should be ready to merge. All tests passed and up to date with main

**Comment by smagnan** [comment]
No conflicts, up to date with main and all checks are passing. Should be ready to merge unless further review is necessary @rlouf

**Comment by rlouf** [comment]
Yes sorry, i haven’t had the time to pull your changes and rebase them yet will do as soon as I can. Thank you for your patience!

**Comment by smagnan** [comment]
No worries. Just wasn't sure what the process for getting PRs merged (since it seems I can add reviewers myself etc). Thanks for the fast feedback!

**Comment by rlouf** [comment]
Thank you for contributing!

**Pull request merged**
