### PR TITLE
introduce WHITESPACE regex constant

### PR DESCRIPTION
**Pull request by jc-louis**
To harmonize with other regexes that are already in constants.

This will also allow to do monkey patching of this regex, to do experiments related to https://github.com/outlines-dev/outlines/issues/484

### CODE REVIEW

**Comment by rlouf** [comment]
This is a very good idea, we might want to be able to pass that as an argument in the near future as well, from our internal experiments it looks like it has a substantial effect on the generation.

**Comment by rlouf** [comment]
It looks like a warning that’s raised in `transfomers` is making the tests fail.

**Comment by Soufiane-Ra** [comment]
+1 for changing outlines/fsm/json_schema.py from whitespace = r"[\n ]* to whitespace = r"[\n ]?" (or just deleting whitespace altogether) to avoid endless generation of new lines

**Comment by rlouf** [comment]
It is not clear from our experiments that this is actually better: https://github.com/outlines-dev/outlines/issues/484. This PR will help a lot with experiments as one can now modify the value of `fsm.json_schema.WHITESPACE`. 

@jc-louis thank you for the PR!

**Pull request merged**
