### PR TITLE
adding better '<fields>' info with schema parser

### PR DESCRIPTION
**Pull request by LeoGrosjean**
- Adding support to type
    ```"<value|type=string>"```
- Adding support to description
    ```"<value|type=string|description=a description>"```
- Adding support to Enum
    ```"<["value_1", ..., "value_n"]|type=string>"```
- Adding support to List[Any]
    ```["<value|type=string>"]```
- Adding support to Format (replace type, tbd if not a good idea)
    ```["<value|format=any>"]```
- Adding fix to nested Object

Test prompt has been updated
Many test runned with openai models, all ending by being able to instanciate custom model 

```python
prompt = prompt_func(NestedModel)
NestedModel(**json.load(model(prompt)))
```

TODO :
- Add support to ```const```
  ```python
  class TemplateValueTask(str, Enum):
      task = "Tâche"
  
  #'TemplateValueTask': {'const': 'Tâche',
  # 'title': 'TemplateValueTask',
  # 'type': 'string'}
  ```
  ```python
  class TemplateValueTask(BaseModel):
    task: Literal["Tâche"]

  # {'properties': {'task': {'const': 'Tâche', 'title': 'Task'}},
  # 'required': ['task'],
  # 'title': 'TemplateValueTask',
  # 'type': 'object'}
  ```

### CODE REVIEW

**Comment by LeoGrosjean** [comment]
broken i monkey patch it (todo added)
use of try except a bit ugly, but do the job until refacto

**Comment by LeoGrosjean** [comment]
For long schema, openai return max 1000 chr => easy to ask chatgpt to finish the json

I will make a way to allow user to tell how many max api call could be made to fulfill the json response
> late but i can detail more

Do you want another pull request for it ?

**Comment by brandonwillard** [comment]
@LeoGrosjean, thanks for the contribution!  We'll follow up shortly with some questions and review comments.

**Comment by LeoGrosjean** [comment]
With xxlarge schema and bad prompt engineering, the output could be text (occured 2 times with a willing confused prompt)
could be controlled if ```outputs[0] not in ["{", "["]```

> with gpt-3.5-turbo

**Comment by LeoGrosjean** [comment]
I'm currently reading [json schema conventions](https://json-schema.org/overview) that pydantic is based on

I'll find a way to code more properly how we will parse schema from ```model_dump_json``` method
> I'm currently rushing and monkey patching it for personal needs; but its working decently
> same *walking* logic could be used elsewhere in outlines

Will update here a mermaid graph with the workflow I figure out
```mermaid
flowchart TD
    A[Model] -->|model_dump_json| B(raw schema)
    value[value]
    type[type]
    format[format]
    description[description]
```

**Comment by rlouf** [comment]
Any updates on this?

**Comment by LeoGrosjean** [comment]
holy kid has arrived, got code on my other computer, need to take time to push it !
> but didnt take time to update the mermaid graph

will do it this week between two diapers :)

**Comment by LeoGrosjean** [comment]
- [x] feature ready
- [ ] code quality (might need a review/peer if anyone available)
- [ ] writing tests for conditions features
- [ ] real life usecase with any transformer

**Pull request closed without merging**
