### PR TITLE
reverting pydantic to v1

### PR DESCRIPTION
**Pull request by atmiguel**

### CODE REVIEW

**Comment by atmiguel** [comment]
sorry this was intended for our fork

**Comment by rlouf** [comment]
You will need to change a few things in the library to revert to v1, not just the dependency.

**Comment by atmiguel** [comment]
Thanks for the heads up! Fortunately, we're not planning on using any of the features related to pydantic right now. We just needed to downgrade the dependency because we have other dependencies that require v1 of pydantic.

**Comment by atmiguel** [comment]
We're just using it for choice-guided generation for now. We do plan on using JSON-guided generation in the future, but we'll cross that bridge when we come to it.

**Pull request closed without merging**
