### PR TITLE
Improvements to documentation and README

### PR DESCRIPTION
**Pull request by rlouf**

### CODE REVIEW

**Comment by viktor-ferenczi** [comment]
The doc is still wrong:
- This command installs vLLM 0.1.2 for me, not the latest 0.2.7: `pip install outlines[serve]`
- The version condition needs to be quoted, otherwise the `>` works as a redirect to file: `pip install pydantic>=2.0`

**Comment by viktor-ferenczi** [comment]
After uninstalling vllm (0.1.2), upgrading pydantic, installing vllm 0.2.7 and upgrading outlines (it installed 0.0.19) I get this error:
```
vllm 0.2.7 requires pydantic==1.10.13, but you have pydantic 2.5.3 which is incompatible.
Successfully installed outlines-0.0.24 pydantic-2.5.3
```

**Comment by rlouf** [comment]
vLLM just bumped the Pydantic version requirement: https://github.com/vllm-project/vllm/pull/2531

**Comment by viktor-ferenczi** [comment]
What about the other issue, that `pip install outlines[serve]` installs old vLLM (0.1.2) and outline (0.0.19)?

**Pull request merged**
