### PR TITLE
Fix missing spaces in `Tokenizer.convert_token_to_string`

### LINKED ISSUE #273: Llama Models decoding produces white spaces between characters
I have modified the code in transformers.py to allow large models to be loaded using device map like in #264:

```python
model = AutoModelForCausalLM.from_pretrained(model_name, device_map="auto", **model_kwargs)
```
And when I use any llama based model that uses the sequences.py, white spaces appear between characters for some of the words. For example:
```python
model = models.transformers("NousResearch/Llama-2-7b-hf")

class Weapon(str, Enum):
    sword = "sword"
    axe = "axe"
    mace = "mace"
    spear = "spear"
    bow = "bow"
    crossbow = "crossbow"


class Armor(str, Enum):
    leather = "leather"
    chainmail = "chainmail"
    plate = "plate"


class Character(BaseModel):
    name: constr(max_length=10)
    age: int
    armor: Armor
    weapon: Weapon
    strength: int

sequence = generate.json(model, Character)("Give me a character description")
```

```
'{\n    "name":   "dermaplan",\n    "age":  55,\n    "a r m o r":   "plat e",\n    "weapon":   "axe",\n    "s t r e n g t h":  4\n}'
```

I find this only occurs with llama models, this issue did not occur with flacon 7B. I assume there is a llama tokenizer decoding issue somewhere.

### PR DESCRIPTION
**Pull request by brandonwillard**
Closes #273

### CODE REVIEW

**Comment by brandonwillard** [comment]
This probably isn't a general enough fix, but it should be a workable stand-in for Llama models right now, so I'm going to merge this.  @AL-377, still feel free to put in a PR for another approach, especially if you think it will cover more cases.

**Comment by AL-377** [comment]
OK,thanks for your effort！I have tried the codellama model and the result remains the white space,I will keep trying

**Comment by brandonwillard** [comment]
> OK,thanks for your effort！I have tried the codellama model and the result remains the white space,I will keep trying

Which HF tokenizer class is it using?

**Comment by AL-377** [comment]
> > OK,thanks for your effort！I have tried the codellama model and the result remains the white space,I will keep trying
> 
> Which HF tokenizer class is it using?

transformers.models.code_llama.tokenization_code_llama_fast.CodeLlamaTokenizerFast

**Comment by brandonwillard** [comment]
> > > OK,thanks for your effort！I have tried the codellama model and the result remains the white space,I will keep trying
> > 
> > 
> > Which HF tokenizer class is it using?
> 
> transformers.models.code_llama.tokenization_code_llama_fast.CodeLlamaTokenizerFast

Thanks!  We just need to add `CodeLlamaTokenizerFast` to the `isinstance` check in this PR.

**Comment by AL-377** [comment]
> > > > OK,thanks for your effort！I have tried the codellama model and the result remains the white space,I will keep trying
> > > 
> > > 
> > > Which HF tokenizer class is it using?
> > 
> > 
> > transformers.models.code_llama.tokenization_code_llama_fast.CodeLlamaTokenizerFast
> 
> Thanks! We just need to add `CodeLlamaTokenizerFast` to the `isinstance` check in this PR.

But actually I have tried the code here:

**Comment by AL-377** [comment]
> > > > OK,thanks for your effort！I have tried the codellama model and the result remains the white space,I will keep trying
> > > 
> > > 
> > > Which HF tokenizer class is it using?
> > 
> > 
> > transformers.models.code_llama.tokenization_code_llama_fast.CodeLlamaTokenizerFast
> 
> Thanks! We just need to add `CodeLlamaTokenizerFast` to the `isinstance` check in this PR.

But actually I have tried the code: 
self.is_sentencepiece = isinstance(
            self.tokenizer, (LlamaTokenizerFast, LlamaTokenizer,CodeLlamaTokenizer,CodeLlamaTokenizerFast)
        )
        
        And I got the error below:
        │ /outlines/text/generate/regex.py:118 in create_proposal                  │
│                                                                                                  │
│   115 │   │   │   │   │                                                                          │
│   116 │   │   │   │   │   sequence = self.model.tokenizer.decode(readable_tokens)                │
│   117 │   │   │   │   │                                                                          │
│ ❱ 118 │   │   │   │   │   ((_, state_seq),) = find_partial_matches(                              │
│   119 │   │   │   │   │   │   self.regex_fsm,                                                    │
│   120 │   │   │   │   │   │   "".join(sequence),                                                 │
│   121 │   │   │   │   │   │   start_state=last_fsm_state,                                        │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ValueError: not enough values to unpack (expected 1, got 0)

My test.py is just the same as the example  at https://github.com/outlines-dev/outlines#efficient-json-generation-following-a-pydantic-model

**Comment by brandonwillard** [comment]
> > > > > OK,thanks for your effort！I have tried the codellama model and the result remains the white space,I will keep trying
> > > > 
> > > > 
> > > > Which HF tokenizer class is it using?
> > > 
> > > 
> > > transformers.models.code_llama.tokenization_code_llama_fast.CodeLlamaTokenizerFast
> > 
> > 
> > Thanks! We just need to add `CodeLlamaTokenizerFast` to the `isinstance` check in this PR.
> 
> But actually I have tried the code:
> 
> ```python
> self.is_sentencepiece = isinstance(
>             self.tokenizer, (LlamaTokenizerFast, LlamaTokenizer,CodeLlamaTokenizer,CodeLlamaTokenizerFast)
>         )
> ```
> 
> ```
>     And I got the error below:
> ```
> 
> ```
>  │ /outlines/text/generate/regex.py:118 in create_proposal                  │
> │                                                                                                  │
> │   115 │   │   │   │   │                                                                          │
> │   116 │   │   │   │   │   sequence = self.model.tokenizer.decode(readable_tokens)                │
> │   117 │   │   │   │   │                                                                          │
> │ ❱ 118 │   │   │   │   │   ((_, state_seq),) = find_partial_matches(                              │
> │   119 │   │   │   │   │   │   self.regex_fsm,                                                    │
> │   120 │   │   │   │   │   │   "".join(sequence),                                                 │
> │   121 │   │   │   │   │   │   start_state=last_fsm_state,                                        │
> ╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
> ValueError: not enough values to unpack (expected 1, got 0)
> ```
> 
> My test.py is just the same as the example at https://github.com/outlines-dev/outlines#efficient-json-generation-following-a-pydantic-model

Yeah, that looks like a different issue with the Llama models altogether.  I'll check it out.

**Comment by brandonwillard** [comment]
That issue is due to tokens corresponding to empty strings (see https://github.com/outlines-dev/outlines/issues/273#issuecomment-1722126543).  The general issue of empty strings and our regex sampling logic might go beyond this Llama-specific tokenization issue, though.  I've addressed it directly in #272, which replaces and simplifies all the regex logic.

**Pull request merged**
