### PR TITLE
Remove unused arguments from openai generate functions.

### PR DESCRIPTION
**Pull request by HerrIvan**
Removes unused arguments in `generate_base` and `generate_choice` openai model functions.

- self.client was not necessary, as the function already uses a callable pointing to a method of the self.client instance.
- max_tokens is not used in `generate_choice`.
- reduces samples to 1 when calling the openai API in `generate_choice`, as discussed in #368 . This fix is not too relevant, as the extra token-cost generated per call was just `samples-1`, but it corrects the code. Note that the alternative solution suggested is not feasible: One can call the api in parallel, but only with a same prompt. As the different samples diverge, both prompts and masks do so, hence any parallelization should be upstream from the API call.

### CODE REVIEW

**Comment by rlouf** [comment]
Thank you! Can we go all the way and remove it from `generate_base`? Also we don't need the client to be a property of the class.

**Comment by HerrIvan** [comment]
I corrected the argument from `generate_base`. It somehow escaped me, sorry... 
I also removed `client` as a property.

**Comment by HerrIvan** [comment]
- removed `client` from as an argument from generate_base, it somehow escaped me.
- removed as a property from the class. It is created but just stored in the closure.
- Warning: please check if y changes to these kind of arguments ( signature="(),(),(m),()->(s)" ) are ok.

**Comment by rlouf** [comment]
Thank you!

**Pull request merged**
