### PR TITLE
Fix/extend re replacement seq

### PR DESCRIPTION
**Pull request by saattrupdan**
This PR is an extension of https://github.com/outlines-dev/outlines/pull/763, related to extending the `re_replacement_seq` regex.

The new [NorwAI models](https://huggingface.co/NorwAI) use a tokenizer that has the token `�.`, which leads to the same error as was described in the previous issue https://github.com/outlines-dev/outlines/issues/762.

This PR extends the fix from https://github.com/outlines-dev/outlines/pull/763 to deal with this case, as well as adding a unit test to test various tokenizers, and a comment describing why we need the prefix and suffix in the regex.

### CODE REVIEW

**Comment by rlouf** [comment]
`HUGGINGFACE_API_TOKEN` should now be available in actions

**Comment by saattrupdan** [comment]
> `HUGGINGFACE_API_TOKEN` should now be available in actions

That's great, thanks. Are you able to get access to the following models with that token?

1. `meta-llama/Meta-Llama-3-8B`
2. `mistralai/Mistral-7B-v0.3`
3. `google/gemma-2b`
4. `NorwAI/NorwAI-Mistral-7B-instruct`

Those are the culprits of the failing tests.

Also, just to be sure, the `HUGGINGFACE_API_TOKEN` is an [access token](https://huggingface.co/settings/tokens) and not a token for the Hugging Face inference API, right?

**Comment by rlouf** [comment]
It's probably better to do this "manually" indeed.

**Comment by saattrupdan** [comment]
@rlouf Changed the test to a "manual" one now, and all tests pass 🙂

**Comment by rlouf** [comment]
Awesome, thank you!

**Pull request merged**
