### PR TITLE
Fix prompt removal logic and update test case

### PR DESCRIPTION
**Pull request by venondev**
Solves #438

### CODE REVIEW

**Comment by rlouf** [comment]
Could you explain the rationale for this change please? It is quite a big interface change.

**Comment by rlouf** [comment]
Thank your for opening a PR! Is it problematic when streaming as well?

**Comment by venondev** [comment]
Works fine in streaming mode. Probably as we do not have to remove the prompt.

**Comment by rlouf** [comment]
I will need to rebase the merge commit, otherwise this looks good! Thank you for contributing

**Pull request merged**
